#!/usr/bin/env bash
# walkthrough/02-linux-pair.sh
#
# Pair the Linux wlb controller with the Windows host that was just
# prepped by 01-windows-bootstrap.ps1.
#
# What it does:
#   1. Sources walkthrough/local-notes.env (REQUIRED — fail fast if missing).
#   2. Generates an ed25519 keypair at $WLB_KEY if absent.
#   3. Prints the public key + the exact one-liner you paste into
#      C:\Users\<WIN_USER>\.ssh\authorized_keys on the Windows side.
#   4. Waits for your "y" — then writes a wlb profile at
#      workspace/profiles/<WLB_PROFILE>.toml (atomic, mode 600).
#   5. Runs `wlb --profile <WLB_PROFILE> describe` and
#      `wlb --profile <WLB_PROFILE> status` to confirm the pairing.
#
# Re-run is safe: existing key is reused, existing profile is rewritten
# only after explicit confirmation.

set -euo pipefail

# Lock to the system PATH (per the global CLAUDE.md rule for shared servers).
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"
export PYTHONNOUSERSITE=1

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$SCRIPT_DIR/local-notes.env"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
ok()   { printf '\033[32m[ OK ]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[WARN]\033[0m %s\n' "$*"; }
fail() { printf '\033[31m[FAIL]\033[0m %s\n' "$*" >&2; exit 1; }

# ─── 1. Load local-notes.env ─────────────────────────────────────────
if [[ ! -f "$ENV_FILE" ]]; then
    fail "$ENV_FILE not found. Copy local-notes.env.example, fill it in, chmod 600."
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

for var in WIN_HOST WIN_USER WIN_LABEL WLB_KEY WLB_PROFILE; do
    if [[ -z "${!var:-}" ]]; then
        fail "$var is empty in $ENV_FILE"
    fi
done

# Expand ~ in WLB_KEY.
WLB_KEY="${WLB_KEY/#\~/$HOME}"

bold "==> Pair config (from $ENV_FILE)"
echo "  WIN_HOST     = $WIN_HOST"
echo "  WIN_USER     = $WIN_USER"
echo "  WIN_LABEL    = $WIN_LABEL"
echo "  WLB_KEY      = $WLB_KEY"
echo "  WLB_PROFILE  = $WLB_PROFILE"

# ─── 2. Keypair ──────────────────────────────────────────────────────
if [[ -f "$WLB_KEY" ]]; then
    ok "SSH key already exists at $WLB_KEY (reusing)"
else
    bold "==> Generating ed25519 keypair (no passphrase — agent-friendly)"
    mkdir -p "$(dirname "$WLB_KEY")"
    ssh-keygen -t ed25519 -N "" -f "$WLB_KEY" -C "wlb-walkthrough" >/dev/null
    chmod 600 "$WLB_KEY"
    ok "Wrote $WLB_KEY (mode 600)"
fi

PUB_KEY="$(cat "$WLB_KEY.pub")"

# ─── 3. Show install instructions ────────────────────────────────────
bold "==> Install this public key on the Windows host"
cat <<EOF

  On the Windows host (PowerShell as $WIN_USER, not admin):

      \$dir = "C:\\Users\\$WIN_USER\\.ssh"
      if (-not (Test-Path \$dir)) { New-Item -ItemType Directory \$dir | Out-Null }
      Add-Content -Path "\$dir\\authorized_keys" -Value @'
$PUB_KEY
'@
      icacls "\$dir\\authorized_keys" /inheritance:r /grant "\$env:USERNAME:F"

  (If $WIN_USER is in the Administrators group, you can ALSO append the
  key to C:\\ProgramData\\ssh\\administrators_authorized_keys — required
  if you intend to ssh as an admin and run elevated cmds.)

EOF

read -r -p "Pubkey installed? Continue and write the profile? [y/N] " ans
if [[ "${ans,,}" != "y" ]]; then
    warn "Aborted before profile write. Re-run when you're ready."
    exit 0
fi

# ─── 4. Write wlb profile ────────────────────────────────────────────
bold "==> Writing wlb profile workspace/profiles/$WLB_PROFILE.toml"

cd "$REPO_ROOT"
PROFILE_DIR="workspace/profiles"
PROFILE_FILE="$PROFILE_DIR/$WLB_PROFILE.toml"
mkdir -p "$PROFILE_DIR"

# Atomic write via tmp file in same dir + rename.
TMP="$(mktemp "$PROFILE_DIR/.${WLB_PROFILE}.XXXXXX.toml")"
trap 'rm -f "$TMP"' EXIT
cat > "$TMP" <<EOF
# Auto-generated by walkthrough/02-linux-pair.sh.
# Re-run the script to regenerate (existing key is reused).

[host]
transport = "ssh"

[ssh]
host            = "$WIN_HOST"
port            = 22
user            = "$WIN_USER"
key             = "$WLB_KEY"
known_hosts     = "none"          # walkthrough only — pin host key for real use
connect_timeout = 10
EOF
chmod 600 "$TMP"
mv "$TMP" "$PROFILE_FILE"
trap - EXIT
ok "Wrote $PROFILE_FILE (mode 600, known_hosts=none — walkthrough only)"

# ─── 5. Smoke `wlb status` ───────────────────────────────────────────
bold "==> wlb describe (does the registry load?)"
uv run wlb --profile "$WLB_PROFILE" describe | head -10 || fail "wlb describe broke"
ok "describe runs"

bold "==> wlb status (does the SSH handshake succeed?)"
if uv run wlb --profile "$WLB_PROFILE" status; then
    ok "Pairing OK — proceed to walkthrough/03-smoke-tests.sh"
else
    warn "wlb status reported a problem. Common causes:"
    echo "  - Public key not in C:\\Users\\$WIN_USER\\.ssh\\authorized_keys"
    echo "  - File perms on authorized_keys wrong (only $WIN_USER should have access)"
    echo "  - sshd not running (check 'Get-Service sshd' on Windows)"
    echo "  - WIN_HOST unreachable (try 'nc -zv $WIN_HOST 22' from this Linux box)"
    exit 1
fi
